export const psample: LectureData[] = [
    {
        create_id: 5,
        creator: '박광식',
        max_participants: 10,
        current_participants: 7,
        category: '디자인',
        bank_name: '하나은행',
        account_name: '오말자',
        account_number: '525-5225-5355-51',
        price: 38000,
        title: '목공예 전문가를 구합니다.',
        content:
            '안녕하세요, 저는 목공예 분야에 관심이 많아 창업을 고려하고 있는 예비 창업자입니다. 현재는 목공예에 대한 기초 지식을 쌓고 아이디어를 구체화하는 중이지만, 더 많은 정보와 경험을 얻고 싶어서 글을 작성하게 되었습니다. \n\n 목공예 분야에서 창업하신 분들 중에는 성공적으로 사업을 운영하시는 분들이 많을 것으로 예상됩니다. 소중한 경험과 노하우를 공유해주시면 감사하겠습니다. 어떻게 시작했는지, 어려웠던 점은 무엇이었는지, 그리고 성공을 거둔 팁과 노하우에 대해 배우고 싶습니다. \n\n 또한, 목공예 창업 시 고려해야 할 사항, 특히 마케팅, 자금 조달, 재료 구입 등에 관한 조언도 얻고 싶습니다. 이 글을 통해 여러 목공예 창업자 분들과 소통하고 지식을 나누는 소중한 기회가 되기를 기대하며, 읽어주셔서 감사합니다.',
        cycle: '주',
        count: 2,
        start_date: '2024-01-04T10:00:00:00',
        end_date: '2024-03-04T10:00:00:00',
        recruitEnd_date: '2023-08-07T10:00:00:00',
        region: '서울시 용산구',
        image_url: 'https://cdn.pixabay.com/photo/2014/07/01/12/23/clothes-381209_1280.jpg',
        createdDate: '2023-08-06T13:58:05:00',
        status: 'AVAILABLE'
    },
    {
        create_id: 2,
        creator: '곽상훈',
        max_participants: 5,
        current_participants: 4,
        category: '요리',
        bank_name: '오징어뱅크',
        account_name: '김오징',
        account_number: '12311111',
        price: 130000,
        title: '바리스타 자격증을 따고 싶습니다.',
        content:
            '안녕하세요, 커피에 대한 열정을 가지고 있는 학생입니다. 바리스타 자격증을 취득하여 전문적인 커피 제조 기술을 배우고 싶어서 이렇게 글을 적어봅니다.\n\n저는 커피에 대한 관심이 많아서, 정말로 좋은 선생님과 함께 학습하고 싶습니다. 위치는 인천시 서구 근처이며, 일주일에 몇 차례 수업을 듣고 싶습니다. 라떼 아트부터 다양한 원두의 특징까지 배우고 싶습니다.\n\n바리스타 분들 중에서 열정적으로 가르쳐주실 수 있는 선생님을 찾고 있습니다. 함께 멋진 커피 여정을 떠날 선생님을 기다리고 있습니다. 감사합니다!',
        cycle: '주',
        count: 2,
        start_date: '2024-01-25T10:00:00:00',
        end_date: '2024-03-251T10:00:00:00',
        recruitEnd_date: '2023-08-07T10:00:00:00',
        region: '인천시 서구',
        image_url: 'https://cdn.pixabay.com/photo/2019/11/11/15/32/coffee-4618705_1280.jpg',
        createdDate: '2023-08-06T13:58:05:00',
        status: 'AVAILABLE'
    },
    {
        create_id: 4,
        creator: '김오숙',
        max_participants: 10,
        current_participants: 7,
        category: '홈/리빙',
        bank_name: '하나은행',
        account_name: '오말자',
        account_number: '525-5225-5355-51',
        price: 38000,
        title: '포장 이사 창업을 하고 싶습니다.',
        content:
            '안녕하세요! 포장 이사 업체를 창업하려는 입장에서, 더 나은 시작을 위해 경험자 분의 도움을 얻고자 글을 올리게 되었습니다.\n\n 포장 이사 업계에서 성공적인 창업을 위해 필요한 노하우, 고객 서비스 전략, 마케팅 방법, 재무 관리, 그리고 어떤 장비나 시스템을 도입하는 게 효과적인지 등에 대한 다양한 경험을 공유해 주실 포장 이사 창업 경험자분을 찾고 있습니다.\n\n 만일 이 글을 보시는 분들 중에서 포장 이사 업계에서의 경험을 전수해주고 싶으신 분이 계시다면, 언제든지 댓글이나 개인 메시지를 통해 연락 주시면 감사하겠습니다.',
        cycle: '주',
        count: 1,
        start_date: '2024-01-07T10:00:00:00',
        end_date: '2024-02-07T10:00:00:00',
        recruitEnd_date: '2023-08-07T10:00:00:00',
        region: '서울시 용산구',
        image_url: 'https://cdn.pixabay.com/photo/2014/07/01/12/23/clothes-381209_1280.jpg',
        createdDate: '2023-08-06T13:58:05:00',
        status: 'AVAILABLE'
    },
    {
        create_id: 3,
        creator: '방숙자',
        max_participants: 49,
        current_participants: 10,
        category: '디자인',
        bank_name: '신한은행',
        account_name: '김영호',
        account_number: '232-2342-2343-24',
        price: 79000,
        title: '스마트 스토어 운영 경험자를 구합니다.',
        content:
            '저는 스마트 스토어를 처음 운영하고자 하는 입장에서, 경험이 풍부한 분에게 조언을 구하고 싶어서 글을 작성하게 되었습니다. \n\n 스마트 스토어의 성공을 위해 필요한 노하우, 상품 등록과 관리, 마케팅 전략, 고객 서비스, 그리고 어떤 도구나 플랫폼을 활용하는 게 좋은지 등에 대한 다양한 경험을 공유해 주실 스마트 스토어 운영 경험자분을 찾고 있습니다.\n\n 만일 스마트 스토어 운영에 대한 전문성을 전수해주시고 싶은 분이 계시다면, 언제든지 댓글이나 개인 메시지를 통해 연락 주시면 감사하겠습니다. 많은 조언 부탁드립니다. 감사합니다!',
        cycle: '주',
        count: 2,
        start_date: '2023-12-26T10:00:00:00',
        end_date: '2024-01-26T10:00:00:00',
        recruitEnd_date: '2023-08-07T10:00:00:00',
        region: '수원시 장안구',
        image_url: 'https://cdn.pixabay.com/photo/2016/08/17/04/43/template-1599667_1280.png',
        createdDate: '2023-08-06T13:58:05:00',
        status: 'AVAILABLE'
    }
];

export const pListSample: LectureListResponse = {
    content: [
        {
            create_id: 1,
            creator: '이혜경',
            max_participants: 30,
            current_participants: 21,
            category: '요리',
            bank_name: '국민은행',
            account_name: '정은혜',
            account_number: '122-2333-3444-45',
            price: 90000,
            title: '일식 요식업 경력자를 찾습니다.',
            content:
                '안녕하세요, 강좌 수강 메뉴에 일식 요식업 강좌가 없어서 제안 드립니다. 일식당 개업을 준비중이며, 위치는 대구시 수성구 근처였으면 좋겠습니다.\n\n 제가 원하는 일식 요리는 라멘이며, 돈부리 등의 덮밥도 연구 중에 있습니다. 창업에 필요한 실무 경험이 풍부하고, 열정적으로 비법을 전수해줄 수 있으신 경력자 분이었으면 좋겠습니다. \n\n궁금한 점이 있으신 분은 언제든지 아래 문의 전화번로 연락주시면 됩니다. ',
            cycle: '주',
            count: 2,
            start_date: '2024-01-10T10:00:00:00',
            end_date: '2024-04-10T10:00:00:00',
            recruitEnd_date: '2023-08-07T10:00:00:00',
            region: '대구시 수성구',
            image_url: 'https://cdn.pixabay.com/photo/2017/04/04/00/36/ramen-2199962_1280.jpg',
            createdDate: '2023-08-06T13:58:05:00',
            status: 'AVAILABLE'
        },
        {
            create_id: 2,
            creator: '곽상훈',
            max_participants: 5,
            current_participants: 4,
            category: '요리',
            bank_name: '오징어뱅크',
            account_name: '김오징',
            account_number: '12311111',
            price: 130000,
            title: '바리스타 자격증을 따고 싶습니다.',
            content:
                '안녕하세요, 커피에 대한 열정을 가지고 있는 학생입니다. 바리스타 자격증을 취득하여 전문적인 커피 제조 기술을 배우고 싶어서 이렇게 글을 적어봅니다.\n\n저는 커피에 대한 관심이 많아서, 정말로 좋은 선생님과 함께 학습하고 싶습니다. 위치는 인천시 서구 근처이며, 일주일에 몇 차례 수업을 듣고 싶습니다. 라떼 아트부터 다양한 원두의 특징까지 배우고 싶습니다.\n\n바리스타 분들 중에서 열정적으로 가르쳐주실 수 있는 선생님을 찾고 있습니다. 함께 멋진 커피 여정을 떠날 선생님을 기다리고 있습니다. 감사합니다!',
            cycle: '주',
            count: 2,
            start_date: '2024-01-25T10:00:00:00',
            end_date: '2024-03-251T10:00:00:00',
            recruitEnd_date: '2023-08-07T10:00:00:00',
            region: '인천시 서구',
            image_url: 'https://cdn.pixabay.com/photo/2019/11/11/15/32/coffee-4618705_1280.jpg',
            createdDate: '2023-08-06T13:58:05:00',
            status: 'AVAILABLE'
        },
        {
            create_id: 3,
            creator: '방숙자',
            max_participants: 49,
            current_participants: 10,
            category: '디자인',
            bank_name: '신한은행',
            account_name: '김영호',
            account_number: '232-2342-2343-24',
            price: 79000,
            title: '스마트 스토어 운영 경험자를 구합니다.',
            content:
                '저는 스마트 스토어를 처음 운영하고자 하는 입장에서, 경험이 풍부한 분에게 조언을 구하고 싶어서 글을 작성하게 되었습니다. \n\n 스마트 스토어의 성공을 위해 필요한 노하우, 상품 등록과 관리, 마케팅 전략, 고객 서비스, 그리고 어떤 도구나 플랫폼을 활용하는 게 좋은지 등에 대한 다양한 경험을 공유해 주실 스마트 스토어 운영 경험자분을 찾고 있습니다.\n\n 만일 스마트 스토어 운영에 대한 전문성을 전수해주시고 싶은 분이 계시다면, 언제든지 댓글이나 개인 메시지를 통해 연락 주시면 감사하겠습니다. 많은 조언 부탁드립니다. 감사합니다!',
            cycle: '주',
            count: 2,
            start_date: '2023-12-26T10:00:00:00',
            end_date: '2024-01-26T10:00:00:00',
            recruitEnd_date: '2023-08-07T10:00:00:00',
            region: '수원시 장안구',
            image_url: 'https://cdn.pixabay.com/photo/2016/08/17/04/43/template-1599667_1280.png',
            createdDate: '2023-08-06T13:58:05:00',
            status: 'AVAILABLE'
        },
        {
            create_id: 4,
            creator: '김오숙',
            max_participants: 10,
            current_participants: 7,
            category: '홈/리빙',
            bank_name: '하나은행',
            account_name: '오말자',
            account_number: '525-5225-5355-51',
            price: 38000,
            title: '포장 이사 창업을 하고 싶습니다.',
            content:
                '안녕하세요! 포장 이사 업체를 창업하려는 입장에서, 더 나은 시작을 위해 경험자 분의 도움을 얻고자 글을 올리게 되었습니다.\n\n 포장 이사 업계에서 성공적인 창업을 위해 필요한 노하우, 고객 서비스 전략, 마케팅 방법, 재무 관리, 그리고 어떤 장비나 시스템을 도입하는 게 효과적인지 등에 대한 다양한 경험을 공유해 주실 포장 이사 창업 경험자분을 찾고 있습니다.\n\n 만일 이 글을 보시는 분들 중에서 포장 이사 업계에서의 경험을 전수해주고 싶으신 분이 계시다면, 언제든지 댓글이나 개인 메시지를 통해 연락 주시면 감사하겠습니다.',
            cycle: '주',
            count: 1,
            start_date: '2024-01-07T10:00:00:00',
            end_date: '2024-02-07T10:00:00:00',
            recruitEnd_date: '2023-08-07T10:00:00:00',
            region: '서울시 용산구',
            image_url: 'https://cdn.pixabay.com/photo/2014/07/01/12/23/clothes-381209_1280.jpg',
            createdDate: '2023-08-06T13:58:05:00',
            status: 'AVAILABLE'
        },
        {
            create_id: 5,
            creator: '박광식',
            max_participants: 10,
            current_participants: 7,
            category: '디자인',
            bank_name: '하나은행',
            account_name: '오말자',
            account_number: '525-5225-5355-51',
            price: 38000,
            title: '목공예 전문가를 구합니다.',
            content:
                '안녕하세요, 저는 목공예 분야에 관심이 많아 창업을 고려하고 있는 예비 창업자입니다. 현재는 목공예에 대한 기초 지식을 쌓고 아이디어를 구체화하는 중이지만, 더 많은 정보와 경험을 얻고 싶어서 글을 작성하게 되었습니다. \n\n 목공예 분야에서 창업하신 분들 중에는 성공적으로 사업을 운영하시는 분들이 많을 것으로 예상됩니다. 소중한 경험과 노하우를 공유해주시면 감사하겠습니다. 어떻게 시작했는지, 어려웠던 점은 무엇이었는지, 그리고 성공을 거둔 팁과 노하우에 대해 배우고 싶습니다. \n\n 또한, 목공예 창업 시 고려해야 할 사항, 특히 마케팅, 자금 조달, 재료 구입 등에 관한 조언도 얻고 싶습니다. 이 글을 통해 여러 목공예 창업자 분들과 소통하고 지식을 나누는 소중한 기회가 되기를 기대하며, 읽어주셔서 감사합니다.',
            cycle: '주',
            count: 2,
            start_date: '2024-01-04T10:00:00:00',
            end_date: '2024-03-04T10:00:00:00',
            recruitEnd_date: '2023-08-07T10:00:00:00',
            region: '서울시 용산구',
            image_url: 'https://cdn.pixabay.com/photo/2014/07/01/12/23/clothes-381209_1280.jpg',
            createdDate: '2023-08-06T13:58:05:00',
            status: 'AVAILABLE'
        }
    ],
    totalElements: 0,
    totalPages: 0,
    number: 0
};
